package com.vestel.tv.middleware;

/**
 * @brief Defines the pictures modes that are displayed under the picture settings of Android device
 */
@SuppressWarnings("unused")
public enum VestelPictureMode
{
    PICTURE_MODE_INVALID,

    // STANDARD PICTURE MODES

    PICTURE_MODE_USER,
    PICTURE_MODE_STANDARD,
    PICTURE_MODE_VIVID,
    PICTURE_MODE_SPORT,
    PICTURE_MODE_MOVIE,
    PICTURE_MODE_GAME,
    PICTURE_MODE_ENERGY_SAVING,
    PICTURE_MODE_HI_BRIGHT,
    PICTURE_MODE_AI_PQ,
    PICTURE_MODE_IMAX,

    // HDR PICTURE MODES

    PICTURE_MODE_USER_HDR,
    PICTURE_MODE_STANDARD_HDR,
    PICTURE_MODE_VIVID_HDR,
    PICTURE_MODE_SPORT_HDR,
    PICTURE_MODE_MOVIE_HDR,
    PICTURE_MODE_GAME_HDR,
    PICTURE_MODE_ENERGY_SAVING_HDR,

    // HDR PLUS PICTURE MODES

    PICTURE_MODE_USER_HDR_PLUS,
    PICTURE_MODE_STANDARD_HDR_PLUS,
    PICTURE_MODE_VIVID_HDR_PLUS,
    PICTURE_MODE_SPORT_HDR_PLUS,
    PICTURE_MODE_MOVIE_HDR_PLUS,
    PICTURE_MODE_GAME_HDR_PLUS,
    PICTURE_MODE_ENERGY_SAVING_HDR_PLUS,

    // HLG PICTURE MODES

    PICTURE_MODE_USER_HLG,
    PICTURE_MODE_STANDARD_HLG,
    PICTURE_MODE_VIVID_HLG,
    PICTURE_MODE_SPORT_HLG,
    PICTURE_MODE_MOVIE_HLG,
    PICTURE_MODE_GAME_HLG,
    PICTURE_MODE_ENERGY_SAVING_HLG,

    // DOLBY VISION PICTURE MODES

    PICTURE_MODE_DOLBY_VISION_BRIGHT,
    PICTURE_MODE_DOLBY_VISION_DARK,
    PICTURE_MODE_DOLBY_VISION_VIVID,
    PICTURE_MODE_DOLBY_VISION_GAME,
    PICTURE_MODE_DOLBY_VISION_IQ,

    // FILMMAKER PICTURE MODES

    PICTURE_MODE_FILMMAKER,
    PICTURE_MODE_FILMMAKER_HDR,
    PICTURE_MODE_FILMMAKER_DOLBY_VISION,
    PICTURE_MODE_FILMMAKER_DOLBY_VISION_IQ
}
