package com.vestel.tv.middleware;

public enum VestelPvrState {
    RECORD_PVR_NTFY_VIEW_STATUS_RECORDING,
    RECORD_PVR_NTFY_VIEW_SCHEDULE_START,
    RECORD_PVR_NTFY_CONTROLLER_CHANNEL_READY,
    RECORD_PVR_NTFY_VIEW_STATUS_STOPPED,
    TIMESHIFT_PVR_START,
    TIMESHIFT_PVR_START_2,
    TIMESHIFT_PVR_STOP,
    RECORDED_MEDIA_PLAY,
    RECORDED_MEDIA_STOP,
    UNKNOWN
}
